services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.6
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # TCP native protocol
      - "9009:9009" # Interserver communication
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./flags:/var/lib/clickhouse/flags
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: defaultpass
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
